INSERT INTO SHOP(NAME, MIN_ORDER_AMOUNT) VALUES('오겹돼지', 13000);
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'MONDAY', '00:00', '23:59');
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'TUESDAY', '00:00', '23:59');
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'WEDNESDAY', '00:00', '23:59');
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'THURSDAY', '00:00', '23:59');
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'FRIDAY', '00:00', '23:59');
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'SATURDAY', '00:00', '23:59');
INSERT INTO OPERATION_HOURS(SHOP_ID, DAY_OF_WEEK, START_TIME, END_TIME) VALUES(1, 'SUNDAY', '00:00', '23:59');

INSERT INTO MENU(SHOP_ID, MENU_NAME, MENU_DESCRIPTION, OPEN) VALUES(1, '삼겹살 1인세트', '삼겹살 + 야채세트 + 김치찌개 + 공기밥1개', 1);

INSERT INTO OPTION_GROUP(MENU_ID, NAME, MANDATORY) VALUES(1, '기본', 1);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(1, '소(250g)', 12000);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(1, '중(400g)', 16000);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(1, '대(600g)', 20000);

INSERT INTO OPTION_GROUP(MENU_ID, NAME, MANDATORY) VALUES(1, '맛선택', 0);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(2, '일반맛', 0);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(2, '매콤맛', 1000);

INSERT INTO OPTION_GROUP(MENU_ID, NAME, MANDATORY) VALUES(1, '추가선택', 0);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(3, '부추재래기 추가', 1000);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(3, '야채세트 추가', 1000);
INSERT INTO OPTION(OPTION_GROUP_ID, NAME, PRICE) VALUES(3, '고기(100g) 추가', 5000);

INSERT INTO CART(USER_ID) VALUES(1);